// using System;
// namespace GoogleTestAdapter.Common { public static class Functional {public static Func<TArgument, TAnonymousReturnType> ToFunc<TArgument, TAnonymousReturnType>(Func<TArgument, TAnonymousReturnType> lambda)
// {return lambda;}}}

                                                                                                                                                                                                                                                       /// <summary> 
                                                                                                                                                                                                                                                       /// defines two functional methods, `square` and `cube`, that take an integer input 
                                                                                                                                                                                                                                                       /// and return its square or cube, respectively. The functions are converted to delegates 
                                                                                                                                                                                                                                                       /// using `Functional.ToFunc()`, and their outputs are printed to the console. 
                                                                                                                                                                                                                                                       /// </summary> 
                                                                                                                                                                                                                                                       /// <param name="args"> 
                                                                                                                                                                                                                                                       /// 0 or more command line arguments passed to the program when it is executed, which 
                                                                                                                                                                                                                                                       /// are ignored in this example function. 
                                                                                                                                                                                                                                                       /// </param> 
using System;namespace GoogleTestAdapter.Common{public static class Functional{public static Func<TArgument, TAnonymousReturnType> ToFunc<TArgument, TAnonymousReturnType>(Func<TArgument, TAnonymousReturnType> lambda){return lambda;}}class Program{static void Main(string[] args){Func<int, int> square = x => x * x;Func<int, int> cube = x => x * x * x;Func<int, int> squareFunc = Functional.ToFunc(square);Func<int, int> cubeFunc = Functional.ToFunc(cube);Console.WriteLine("Square of 5: " + squareFunc(5));Console.WriteLine("Cube of 3: " + cubeFunc(3));}}}

