def deeply_nested_function(x):
    def inner_function_1(y):
        def inner_function_2(z):
            def inner_function_3(a):
                def inner_function_4(b):
                    def inner_function_5(c):
                        def inner_function_6(d):
                            def inner_function_7(e):
                                def inner_function_8(f):
                                    def inner_function_9(g):
                                        def inner_function_10(h):
                                            def inner_function_11(i):
                                                def inner_function_12(j):
                                                    def inner_function_13(k):
                                                        def inner_function_14(l):
                                                            def inner_function_15(m):
                                                                def inner_function_16(n):
                                                                    def inner_function_17(o):
                                                                        def inner_function_18(p):
                                                                            def inner_function_19(q):
                                                                                def inner_function_20(r):
                                                                                    def inner_function_21(s):
                                                                                        def inner_function_22(t):
                                                                                            def inner_function_23(u):
                                                                                                def inner_function_24(v):
                                                                                                    def inner_function_25(w):
                                                                                                        def inner_function_26(x):
                                                                                                            return w + x
                                                                                                        return inner_function_26(x)
                                                                                                    return inner_function_25(w)
                                                                                                return inner_function_24(v)
                                                                                            return inner_function_23(u)
                                                                                        return inner_function_22(t)
                                                                                    return inner_function_21(s)
                                                                                return inner_function_20(r)
                                                                            return inner_function_19(q)
                                                                        return inner_function_18(p)
                                                                    return inner_function_17(o)
                                                                return inner_function_16(n)
                                                            return inner_function_15(m)
                                                        return inner_function_14(l)
                                                    return inner_function_13(k)
                                                return inner_function_12(j)
                                            return inner_function_11(i)
                                        return inner_function_10(h)
                                    return inner_function_9(g)
                                return inner_function_8(f)
                            return inner_function_7(e)
                        return inner_function_6(d)
                    return inner_function_5(c)
                return inner_function_4(b)
            return inner_function_3(a)
        return inner_function_2(z)
    return inner_function_1(x)
